### ISSUE TITLE
[Feature Request] Add support for vim's terminal

### ISSUE THREAD

**Issue by 4513ECHO** [tobi-wan-kenobi/zengarden#1]
There is only neovim's terminal support now:
https://github.com/tobi-wan-kenobi/zengarden/blob/main/colors/zengarden.vim#L244-L268
Could you consider of vim's it?

**Comment by tobi-wan-kenobi** [comment]
I will gladly look into it, however, I have to stress that I know next to nothing about this roght now, ao it might take me a while to get right :)

Could you maybe describe to me what scenario needs to work for you? (ie. terminal environment, etc)

**Comment by 4513ECHO** [comment]
We only have to define `g:terminal_ansi_colors`. It is array of color code, and its order is same as neovim's it.

ref: https://vi.stackexchange.com/questions/21345/how-does-gterminal-ansi-colors-affect-the-terminal-colors

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot!

The commit right now should fix it at least partially (in gvim, at least, the background is still completely black/white, depending on the `background` setting).

Hope this helps you!
