### ISSUE TITLE
Some colours are different in neovim 0.10.0

### ISSUE THREAD

**Issue by luator** [tobi-wan-kenobi/zengarden#4]
I just upgraded to neovim 0.10.0 and noticed that some colours are not set correctly anymore.

The upper panel in the screenshot below uses neovim 0.10.0, the lower one 0.9.5.  Settings, plugins, etc. are identical.

![image](https://github.com/tobi-wan-kenobi/zengarden/assets/9333121/4183fca8-e698-45ae-a931-11e236a05560)

According to the [release notes of 0.10](https://neovim.io/doc/user/news-0.10.html) there were some changes affecting the default colours.  I guess this causes the difference.

> Default color scheme has been updated to be "Nvim branded" and accessible. Use :colorscheme vim to revert to the old legacy color scheme.
> * These Nvim specific highlight groups are now defined in a meaningfully different way and might need an update:
>   * hl-FloatBorder is linked to hl-NormalFloat instead of hl-WinSeparator.
>   * hl-NormalFloat is not linked to hl-Pmenu.
>   * hl-WinBar has different background.
>   * hl-WinBarNC is similar to hl-WinBar but not bold.
>   * hl-WinSeparator is linked to hl-Normal instead of hl-VertSplit.
> * This also might result into some color schemes looking differently due to them relying on implicit assumptions about how highlight groups are defined by default. To account for this, define all attributes of highlight groups explicitly. Alternatively, use :colorscheme vim or :source $VIMRUNTIME/colors/vim.lua to restore previous definitions.

I can also try to fix it, but any pointers what/where to change would be helpful, in case you already have some understanding of the issue.

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report! I will look into it, bit it might take a bit.

I guess the easiest start would be to use the zengarden-lush repo and go from there (as far as i can remember, this theme is generated directly from the lush definitions)

**Comment by tobi-wan-kenobi** [comment]
Took me a while, but hopefully, this is fixed now

**Comment by luator** [comment]
Thanks a lot for looking into it!  I wanted to give it a try myself at some point but couldn't figure out what would need to be changed.
There seems to be an issue now, though: light mode is not working anymore.  That is, the background is now dark, even if I set `bg=light`.

**Comment by tobi-wan-kenobi** [comment]
Yeah, I noticed that as well :(

I am working on a complete overhaul right mow, with full treesitter support, stay tuned and thanks for your patience!

**Comment by luator** [comment]
Cool, looking forward to that!  But please don't feel pressured, I'm happy to wait (I simply reverted the last commit locally for now).

**Comment by tobi-wan-kenobi** [comment]
Can you please try to update, when you have a bit of time?

I changed a couple of things and would be happy about feedback. Plus, I probably missed a couple of important highlight groups.

But I tested and light background works again :)

**Comment by luator** [comment]
Hm, light background is still not working for me.  I took a quick look at the changes.  In the past, there was a `if s:is_dark` which seems to be gone now. Maybe you forgot to push some commit?

**Comment by tobi-wan-kenobi** [comment]
I think I somehow messed up the conversion from lush to regular vim colorscheme.

I will look at that, but it will take a bit, sorry about that.

If you want to, you can try switching to the lush scheme in the meantime (zengarden-lush), which *should* work.

**Comment by tobi-wan-kenobi** [comment]
Actially, looking at the code right now, I don't get why it works on my machine.... Stay tuned :)

**Comment by luator** [comment]
With zengarden-lush I do get a light background but the colour is wrong:
![image](https://github.com/tobi-wan-kenobi/zengarden/assets/9333121/2c862e74-b04a-4dfe-81cb-b19e5f1279c2)

Maybe this also depends on other things like colour settings of my terminal?

**Comment by tobi-wan-kenobi** [comment]
I pushed an update to the lush scheme that explicitly switches foreground and background colors on light backgrounds. hope this helps!

the export to vimscript for some reason does not include this, so still looking into that.

**Comment by tobi-wan-kenobi** [comment]
lush is now definitely fixed, I had "dark" hardcoded 🙈

TBH I will probably deprecate the vimscript version at some point, I remembered that this is completely separately maintained, and that is way too much hassle.

**Comment by luator** [comment]
Thanks, I can confirm that the background colour is correct now.  Overall highlighting is much different, though, is that intended?
Left is zengarden (commit 0629911), right is latest version of zengarden-lush:
![image](https://github.com/tobi-wan-kenobi/zengarden/assets/9333121/69af636f-bba8-46ed-b5ce-8991a47f7d23)


> TBH I will probably deprecate the vimscript version at some point, I remembered that this is completely separately maintained, and that is way too much hassle.

Alright, I can totally understand that.

**Comment by tobi-wan-kenobi** [comment]
Oh, thanks for the side by side!

Yeah, well, I am still in the process of fixing the scheme, but some things might stay different.

If there's things you don't like at all, please let me know :)

also, I want to try to have customization to a degree.

**Comment by luator** [comment]
The colours all seem to be a bit lighter, compared to the old version, which results in too low contrast with the background in my opinion.  Apart from that, I don't mind if things change a bit.  It's your theme after all, so do what you prefer!  If I really don't like some parts of it in the end, I can always modify them locally.

**Comment by tobi-wan-kenobi** [comment]
I've changed around some of the colors, I think the contract should be way better now. Also, the code is now much cleaner & easier to modify for dark & light themes.

Thank you very much for your input!

**Comment by luator** [comment]
Thanks a lot for your work!  It looks indeed much better now.  I also took a quick look at the code, looks pretty clean and easy to customise if needed :+1:.  Also, Lush is really useful for that, I didn't know it before :).

**Comment by tobi-wan-kenobi** [comment]
Yes, that's why I am migrating this color scheme over to Lush completely (see #5 ).

If you are curious, just using the `5/lush` branch should give you a decent preview with (partial) integrations for kitty and obsidian already.
Also, I am playing around with making the palette nicer, but no promises there :)

**Comment by tobi-wan-kenobi** [comment]
Closed, as the colors have been (significantly) changed on purpose now (see #5)
